### ISSUE TITLE
Adding blocks to a collection do not always render correctly while Live Preview is open

### ISSUE THREAD

**Issue by tschwartz** [payloadcms/payload#12281]
### Describe the Bug

Adding blocks to a collection do not always render correctly while Live Preview is open, sometimes the loading animation just cycles forever unless the user toggles back to Edit and then back to Live Preview.

### Link to the code that reproduces this issue

https://github.com/tschwartz/payload-cms-repro

### Expected
- Run the project
- Navigate to http://localhost:3000/admin
- Create the default user
- Navigate to the Pages collection
- Create a new page
- Give the page a slug ('home' will work with the root route)
- Click the Live Preview tab/button
- Add a Rich Text content block
- Observe that the Rich Text content renders a form element
- Enter some content, or don't
- Add another Rich Text content block
- Observe that the Rich Text content renders a form element

### Observed

- Run the project
- Navigate to http://localhost:3000/admin
- Create the default user
- Navigate to the Pages collection
- Create a new page
- Give the page a slug ('home' will work with the root route)
- Click the Live Preview tab/button
- Add a Rich Text content block
- Observe that the Rich Text content renders a form element
- Enter some content or don't
- Add another Rich Text content block
- Observe that the Rich Text content loading animation does not stop and reveal a form element

Note, this is not specific to the Rich Text block but all content block types.

<img width="621" alt="Image" src="https://github.com/user-attachments/assets/4dbebe21-b8b7-4076-ae04-d285d97a447f" />

### Which area(s) are affected? (Select all that apply)

Not sure

### Environment Info

```text
Binaries:
  Node: 20.18.1
  npm: 11.3.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.35.1
  next: 15.2.4
  @payloadcms/graphql: 3.35.1
  @payloadcms/live-preview: 3.35.1
  @payloadcms/live-preview-react: 3.35.1
  @payloadcms/next/utilities: 3.35.1
  @payloadcms/richtext-lexical: 3.35.1
  @payloadcms/translations: 3.35.1
  @payloadcms/ui/shared: 3.35.1
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:39 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6020
  Available memory (MB): 65536
  Available CPU cores: 12
```

**Comment by DanRibbens** [comment]
@tschwartz thank you for providing access to the repo.

I was able to observe the error once but then it wasn't occuring again. How often are you able to reproduce it?
I'm not sure how to prioritize this one without consistent reproduction or an example of the error if there is one.

Let us know!

**Comment by tschwartz** [comment]
Hello @DanRibbens I am able to reproduce the issue every time using the repro steps provided above. The issue typically will not present itself on the first content block added but rather on every instance thereafter.

**Comment by tschwartz** [comment]
@DanRibbens I have pushed up a minimal repro, removing everything but the pages collection, all extraneous dependencies, etc and am still able to reproduce the issue using the steps above. That said, I am not able to reproduce this with the Payload website template...

**Comment by Rybadour** [comment]
I came here today to report this bug as well. We've noticed it seems to happen only for blocks that would have validation errors such as ones with required fields.

**Comment by peterkunsay** [comment]
+1, We're experiencing the same issue where the loading animation cycles forever when adding new blocks. For us, this seems to occur much more frequently on macOS compared to Windows. Reloading the page solves the issue temporarily, but only for the first few new blocks before it starts happening again.

**Comment by JessRynkar** [comment]
Is anyone still experiencing this on the latest version `v3.72.0`?

**Comment by JessRynkar** [comment]
Since we haven’t heard back in a while and this issue relates to several releases ago, we’re going to close it for now. If you’re still seeing this behavior on the latest version (v3.74.0), please let me know and we can re-open this.

**Comment by tschwartz** [comment]
Can confirm, have not seen in a number of versions. Thank you.
