### ISSUE TITLE
The text field with the hasMany option enabled is not compatible with CJK IME input

### ISSUE THREAD

**Issue by rktyt** [payloadcms/payload#12427]
### Describe the Bug.

The handling of Tab and Enter key presses is inadequate, resulting in unintended behavior.

I'm using Google's Japanese Input Method Editor (IME) available at https://www.google.co.jp/ime/ for text input.
In Chrome 136.0.7103.114, pressing the Enter key while using Japanese input causes the input value to be duplicated like this.
<video src="https://github.com/user-attachments/assets/acc145de-3863-4925-aced-33dda9a39556"/>

When the Tab key is pressed, it is supposed to select a conversion candidate, but instead, the input is being confirmed as shown below.
<video src="https://github.com/user-attachments/assets/59b7fc5b-7ba0-4cae-b039-d5a15eb79aad"/>

Note: The behavior may differ depending on the browser. As for Firefox, it is currently working as expected.

### Reproduction Steps

```typescript
fields: [
  {
    name: 'options',
    label: '選択肢',
    type: 'text',
    hasMany: true,
    localized: true,
  },
]
```

And use an IME for CJK input.

If you also consider the following information, it should be possible to reproduce and fix the issue.
- https://github.com/adobe/react-spectrum/pull/5923
- https://github.com/adobe/react-spectrum/pull/6239
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing
- https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent

### Environment Info

```text
Payload: 3.38.0
Node.js: 22.12.0
Next.js: 15.3.2
```

**Comment by Robot-Inventor** [comment]
I could not reproduce this issue in my environment. My environment is as follows:

- OS: Windows 11 25H2 (build 26200.7462)
- Browser: Chrome 143.0.7499.170
- Node.js v25.2.1
- Payload 3.69.0
- Next.js 15.4.10
- Google Japanese Input 2.32.5990.0

When I created a simple verification code and checked, the Enter or Tab keydown events were no longer being sent during IME composition, so it is possible that this has been fixed in Windows or Chrome.

https://github.com/user-attachments/assets/3548378e-0ba0-4aff-b7c2-8127c9b4c60b

@rktyt Is this problem still occurring in your environment?

**Comment by rktyt** [comment]
@Robot-Inventor It still occurring.

OS: MacOS 15.7.1（24G231）
Browsers:
- Chrome 143.0.7499.170 (arm64)
- Edge 143.0.3650.96(arm64)
- Safari 26.0.1 (20622.1.22.118.4)
Google Japanese Input: 2.32.5990.1

payload: 3.69.0
next: 15.4.10

-----

The issue does not occur with Firefox (developer edition) 147.0b9 (aarch64).

**Comment by Robot-Inventor** [comment]
@rktyt I was able to reproduce this issue using macOS and Chrome and fix it locally, so I will submit a pull request later.
