### ISSUE TITLE
Cannot edit focal on image with s3Adapter

### ISSUE THREAD

**Issue by felskov** [payloadcms/payload#5112]
### Describe the Bug

When uploading a new image, I'm able to select a focal point. If I try to edit that same image a later point in time, trying to change the focal point, I consistently get an error message and nothing happens.

From inspecting the error message, I've been able to tell that the issue occurs inside "uploads/generateFileData.ts", specifically I seems that the URL is malformed when using external storage of files. It seems to be due to the fact that a baseUrl is prepended to the URL, which probably shouldn't be done when disableLocalStorage is enabled.

For instance, I see that the endpoint tries to request this URL:

```text
http://payload.localhosthttp//payload.localhost/media/Screenshot%202024-02-07%20at%2013.35.02.png
```

Obviously this will fail, causing the entire edit image feature to be unavailable.

### To Reproduce

1. Upload a new image
2. Click the edit-icon on the image info
3. Click "Edit image" (again) inside the overlay
4. Change focal point
5. Click "Apply changes"
6. Click "Save" (the error message will now be displayed)

--

By the way, why do we need to click "edit" and "apply/save" twice? Seems like a poor UX as the initial overlay doesn't provide any more information to the user than what he could already see. Not really related to this bug, but mentioning anyway :)

### Payload Version

2.9.0

### Adapters and Plugins

@payloadcms/plugin-cloud-storage/s3

**Comment by kariyngva** [comment]
I think this might be the same issue as https://github.com/payloadcms/payload/issues/5000 which should be solved in 2.11.1 via https://github.com/payloadcms/payload/pull/5034

**Comment by denolfe** [comment]
Thanks for the write-up @felskov. @kariyngva is correct, this looks to be the same issue that was fixed.

Feel free to reopen if you try the latest version and still have issues 👍

**Comment by felskov** [comment]
@denolfe Apologies, I should've tried to upgrade before opening the issue. I did try to search for similar issues, but didn't find #5000 as I think I was too focussed on focal points and didn't think about searching for general issues related to editing images.

Thanks for the heads up, we will try to upgrade - and from what I can tell you're right that this should fix the issue we were seeing 👍 

Also, and feel free to disregard this, but I can't help but feel like the solution in 25cee8b is a bit icky with a custom implementation of URL resolving. Wouldn't it be better to do something along the lines of the following example? That should also work correctly, in case an adapter should ever attempt to use e.g. data URIs :) 

```ts
const baseUrl = req.get('origin') || `${req.protocol}://${req.get('host')}`;
const fileURL = new URL(url, baseUrl).toString();
```

**Comment by felskov** [comment]
@denolfe We tried upgrading to v2.11.1, and as expected the issue reported in this ticket was resolved, but we're still not able to successfully edit images.

The issue occurs because we're running the application behind a reverse proxy (nginx), which causes the getExternalFile fetch request to stall and time out. This happens due to bad forwarding of headers here:

```ts
const res = await fetch(fileURL, {
  credentials: 'include',
  headers: {
    ...req.headers,
  },
  method: 'GET',
})
```

When we dug into the issue, we realized that this caused you to forward all headers from the incoming request to _edit_ the image. That request is a POST-request, which includes a request body. Therefore that request also contained a "Content-Length" header. But obviously we don't actually send a request body with the above GET-request, and therefore nginx never served the request (it kept waiting for a request body that never came).

I think you might want to be more explicit about which headers to forward (seemingly only cookies are relevant here?), so as to avoid causing issues with applications behind load balancers / reverse proxies / other?

And funnily, if you had used the built-in `fetch` from v18 the application would have thrown a more "correct" error message about trying to send a GET request with a Content-Length header. That would've made our lives easier while debugging this issue :)

Would you like me to open a new ticket detailing this issue, or is it sufficient to re-open this one?

**Comment by denolfe** [comment]
@felskov Yes, this seems like a scenario for a new ticket.
