### ISSUE TITLE
DefaultValue for Number field with hasMany set to true does not work

### ISSUE THREAD

**Issue by skysarwer** [payloadcms/payload#5563]
### Describe the Bug

If you have a number field in a collections config with `hasMany` set to `true`, there is no acceptable defaultValue. 

I've tried arrays of integers, `[30, 7, 1]`  which returns an error `ERROR (payload): 1: Collection "collection-slug" > Field "field_name" > "value" does not match any of the allowed types`

I've also tried with an array of strings to same effect. Passing raw integers, i.e `30` doesn't have an error but doesn't get populated either. 

### To Reproduce

Try to set a defaultValue to a number field with `hasMany` set to `true`

### Payload Version

2

**Comment by JessChowdhury** [comment]
Fixed [here](https://github.com/payloadcms/payload/pull/5618).

**Comment by skysarwer** [comment]
> Fixed [here](https://github.com/payloadcms/payload/pull/5618).
npm update @payloadcms/payload
Thank you! Do you know if this version is published to npm yet? 

I tried running `npm update @payloadcms/payload` , setting the default value and running but am getting the same error still. Screenshot below : 

![Screenshot 2024-04-04 182638](https://github.com/payloadcms/payload/assets/81714339/3d9d9547-bb7c-442b-8fc6-4d0f8aee2117)
