### ISSUE TITLE
[Bug](Versions): Autosave fails when there exists a unique field

### ISSUE THREAD

**Issue by hunghvu** [payloadcms/payload#953]
# Bug Report

Whenever a field of a collection is `unique`, the autosave mechanism only works with the first item in the collection, and always fails for later items.

## Expected Behavior

Autosave should always work even if there exists a unique field.

## Current Behavior

Autosave event is fired upon new item collection. This ignores the `required` and `unique` status of fields. When the first item in the collection is created (leave all fields empty), there is no `unique` constraint violation, so it saves normally. However, upon the second item creation (still empty fields at this stage), `unique` constraint is violated. After autosave fails, it does not function anymore (even after fields are updated). 
  - Empty collection => Create item 1 => Autosave _unique_ empty fields upon creation => Success
  - Create item 2 => Autosave empty fields => Violate `unique` constraint => Fail

There is one thing that confuses me, autosave still fails after I set the value for the unique field of the first item. 
  - Empty collection => Create item 1 => Autosave _unique_ empty fields upon creation => Update unique field value to `123` => Autosave => Success
  - Create item 2 => Autosave empty fields upon creation => Fail?

If I manually save the second (or later) items by publishing changes, then the autosave mechanism starts to work again.

![image](https://user-images.githubusercontent.com/62678592/185270728-2b633f5a-ceff-4e94-a33d-600f368762a4.png)

## Possible Solution

1. Autosave should start only after all `required` and `unique` fields are filled. 
2. Autosave exception message should clarify the cause of the error (e.g., `unique` constraint violation), and require users to fix it before the next save.
3. Ensure autosave can rerun even after exception.

## Steps to Reproduce

1. Create a `Test` collection as below.
```ts
import { CollectionConfig } from 'payload/types';

const Test: CollectionConfig = {
  slug: 'test',
  fields: [
    {
      name: 'uniqueField',
      label: 'Unique field',
      type: 'text',
      unique: true
    },
    {
      name: 'content',
      label: 'Non-unique field',
      type: 'text'
    }
  ],
  timestamps: true,
  versions: {
    drafts: {
      autosave: true,
    },
  },
};

export default Test;
```
2. Create the first item in the collection. Leave all the fields empty or fill them with something (autosave successfully).
3. Create the second item in the collection => Autosave fails.

## Detailed Description

Tested on:
  - Payload: 1.0.25
  - MongoDB: 6.0.0 Community
  - Related issues or discussion: None

**Comment by jmikrut** [comment]
Hey @hunghvu — I think this was recently fixed. Can you validate my thoughts by taking a look into your versions database for your autosave collection, and manually removing any `unique` indexes that might be present in your versions collection? Then restart Payload and see if they are recreated? There should be _**no**_ unique indexes within versions collections at this point.

Let me know and thanks for the report!

**Comment by hunghvu** [comment]
Hi @jmikrut, I don't see any abnormal unique indexes, as seen in the screenshot below. I also delete the database and regenerate it from scratch, but to no avail.

![image](https://user-images.githubusercontent.com/62678592/185283126-7ebf76fb-a6b9-4370-8156-c31b3c6c06a5.png)

When checking items in the database, I wonder why the saved item (with empty fields) does not show up. 

![image](https://user-images.githubusercontent.com/62678592/185284343-50f9da79-761b-4bcf-8266-d87c111780f1.png)

Also, when deleting the item, its version does not go away.

![image](https://user-images.githubusercontent.com/62678592/185284447-25c03b94-98e7-420f-a6cb-e3c519d7d118.png)

![image](https://user-images.githubusercontent.com/62678592/185284746-2bf4d2b3-a24c-4cb6-9553-b58eef80d515.png)

**Comment by jmikrut** [comment]
Hey @hunghvu — here are some answers for you!

> I don't see any abnormal unique indexes, as seen in the screenshot below. I also delete the database and regenerate it from scratch, but to no avail.

This is actually exactly right! In your screenshot, there _**are no unique indexes in the _versions collection. There should not be.**_ This was your original problem, but this has since been fixed in newer versions of Payload. So, when you dropped your indexes / database and recreated data, it now looks right and autosave should work once again. Does it? Can you now autosave since having cleared your database?

> When checking items in the database, I wonder why the saved item (with empty fields) does not show up.

This is because the _**first**_ version is created in your actual collection. Then, all subsequent versions are created in the `_versions` collection. Basically, we _need_ a first REAL document to exist, so that the `_versions` collection can have the `parent` field point back to the main document. But, that first document created in the main collection will be saved as a `draft` and will not be published. Does that make sense?

> Also, when deleting the item, its version does not go away.

This is a setting that you can control. Have you set `retainDeleted` to false? If this is false, all versions will be deleted when the parent doc is deleted. 👍 

Here are some docs about that.
https://payloadcms.com/docs/versions/overview#collection-config

I believe the issue corresponding to this original thread has since been fixed.

Will you confirm that after deleting your collections / indexes / etc - that you can now autosave correctly?

**Comment by hunghvu** [comment]
@jmikrut  Thanks for the explanation of the deletion mechanism, that makes sense. I did not set any value to that though. Perhaps the document can be improved by clarifying the default values of these options.

Now back to the original thread. The autosave still does not behave correctly as mentioned. I include a video below to demonstrate its current behavior. Hopefully, it is useful.

https://user-images.githubusercontent.com/62678592/185724960-51204739-3c88-4484-be5b-04558c7df536.mp4

**Comment by jmikrut** [comment]
Hey @hunghvu — thank you very much for hanging in here.

I was able to reproduce the problem and know exactly what caused it. The fix is released in `1.0.29`.

Again, THANK YOU!
