### ISSUE TITLE
Default value does not work with select and "required" is ignored.

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload#9661]
### Describe the Bug

With a `select` `Field` and `defaultValue`, upon creating a new document, the `defaultValue` is presented in the field, as intended. However, upon submitting the form to create that document, it is ignored/left empty.

On top of that, this field has `required` set to true. So, even if this isn't done at the database level with SQL adapters, I still think it should still throw an error when a field is marked as required and for whatever reason, it does not receive a value before saving it to the database. Validation does not seem to take place at the right level, in my opinion.

https://github.com/user-attachments/assets/f11e7b1e-38d3-4435-b354-241ec138e7d8

### Link to the code that reproduces this issue

https://github.com/HarleySalas/payload-3-reproductions/tree/defaultvalue-required-select

### Reproduction Steps

You can add a field to any payload collection like this:
```
 {
      name: 'roles',
      type: 'select',
      hasMany: true,
      defaultValue: 'editor',
      required: true,
      options: [
        {
          label: 'Admin',
          value: 'admin',
        },
        {
          label: 'Editor',
          value: 'editor',
        },
      ],
    },
```
or alternatively, clone the reproduction I provided and create a new user once you're logged in, from the admin panel. Up doing so, simply ignore the default value, proceed to create the new user and observe that the value is completely ignored.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Payload: 3.2.2
Node: 22.2.0
NextJS: 15.0.3
```

**Comment by yonnic** [comment]
yea the defaultValue has many issues and i experienced how it overrides existing values on mass edit https://github.com/payloadcms/payload/issues/9590

i hope this gets fixed soon

**Comment by akhrarovsaid** [comment]
I think this was fixed around 3.6.0 along with 9590 and some other related issues! Can't reproduce it in the monorepo using mongo or postgres. @HarleySalas want to confirm on your end?

**Comment by zacuke** [comment]
I ran into a similar issue on a fresh `npx create-payload-app` when I tried to add a Select control to the Contact form that is included in the template. My experience was that defaultValue was ignored and my Select control would render unselected.

The way I fixed it was by modifying `src\blocks\Form\Select\index.tsx`:
- On line 12 add `{ useEffect }` to the import
- On line 27 add `defaultValue` to the list of parameters
- On line 35 right inside render, add a call to `useEffect`:
```javascript
        ...
        render={({ field: { onChange, value } }) => {
          // Trigger onChange with defaultValue if no value is set
          useEffect(() => {
            if (!value && defaultValue) {
              onChange(defaultValue)
            }
          }, [value, defaultValue, onChange])
         const ControlledValue = ... 
```

This seems to fix the page loading so the defaultValue  is respected on initial page load, as well as form submission so the defaultValue is used correctly when the user never touches the Select control.

**Comment by PatrikKozak** [comment]
Hey @HarleySalas, @zacuke, @yonnic - thank you so much for your patience here!

I just tried to reproduce this with the exact config from above and was not able to on v3.24.0.

Any chance you all can update your projects and let me know if its still and issue? 

Thanks!

**Comment by HarleySalas** [comment]
@PatrikKozak I went ahead and [updated my reproduction](https://github.com/HarleySalas/payload-3-reproductions/tree/defaultvalue-required-select) and the issue still occurs.

If you clone the repo, you genuinely only need the data from the `.env.example` and to `pnpm install`. No need for any additional configuration. Just go to [http://localhost:3000/admin](http://localhost:3000/admin) and create the first user. When creating the user, simply ignore the `roles` field completely. If you touch it, it will work. If it remains untouched, the error will occur.

**Comment by zacuke** [comment]
1. I did a fresh `npx create-payload-app` and verified in `node_modules` it used `v3.24.0`
2. Choose SQLite
3. `pnpm install libsql` fixes a missing dependency
4. Use `seed with data`, in order to get a sample Contact form and navigation
5. Edit sample Contact form: add `select` type of field
6. Create 2 entries, for example `A` and `B`
7. Make required

Then upon visiting the Contact form the `select` field is already populated, but the Required field validator is forcing me to manually toggle it. 

![Image](https://github.com/user-attachments/assets/ed4a010b-a252-4d45-b08b-b6b20ab62af7)

Also if I go try to set a Default Value (for example to make it automatically select my 2nd option), that is ignored.

If I apply the `useEffect()` hack mentioned in previous comment, then the `select` field seems to start behaving as expected.

**Comment by PatrikKozak** [comment]
@HarleySalas @zacuke thanks for the additional info and the reproduction repo - this was very helpful.

Looks like its an issue with `sqlite` & `postgres` - working on a fix for this now

Seems to work as expected with `mongodb` interestingly

**Comment by PatrikKozak** [comment]
Hey @HarleySalas & @zacuke, I believe I see the issue.

Your select field is `hasMany: true` but you're only passing a `string` for the `defaultValue`, if you make it an array instead I.e

```
{
  name: 'roles',
  type: 'select',
  hasMany: true,
  defaultValue: [ 'editor' ],
  required: true,
  options: [
    {
      label: 'Admin',
      value: 'admin',
    },
    {
      label: 'Editor',
      value: 'editor',
    },
  ],
},
```

The issue should be resolved. 

I will however implement a fix on the type level that will require `defaultValue` to be of type `array` if the field has `hasMany: true` on it.

**Comment by PatrikKozak** [comment]
I'll go ahead and close this issue since the fix is to wrap the `defaultValue` in brackets.

For future improvements, I’ve opened a discussion to track an enhancement that would enforce arrays for defaultValue when hasMany: true. Feel free to check it out and add any thoughts: https://github.com/payloadcms/payload/discussions/11304

Let me know if this works for you or if you're still experiencing any issues here!
